version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatlabsdb
    ports:
      - '5432:5432'

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/chatlabsdb
      CRON_INTERVAL: 1
    depends_on:
      - postgres
    ports:
      - '3000:3000'
